//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductXSupplier
    {
        public int IDProductXSupplier { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDSupplier { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
